### ISSUE TITLE
Database Access

### ISSUE THREAD

**Issue by proff321** [TechneauxCMPS/Ticket-API#8]
Please email me the IP addresses of the locations that will be used to access the database.  I'll have to whitelist the IPs in order for the team to access the database.

**Comment by tlanclos** [comment]
Can you just put the server you gave us to develop on in the whitelist? We should be able to inspect the database from there if we need.

**Comment by proff321** [comment]
That's a great idea!  I'll put the login information in your home folder on the server.

**Comment by tlanclos** [comment]
Awesome, sounds great

**Comment by proff321** [comment]
All done.
